#!/usr/bin/env python3
"""Generate ssign pipeline summary report (HTML + text).

Summarizes: genome count, protein count, SS system counts, substrate counts,
annotation tool coverage, and key parameters.
"""

import argparse
import logging
import os
from collections import Counter
from datetime import datetime

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# Annotation tools grouped by the column prefixes each one contributes. A
# secreted protein counts as "covered" by a tool if ANY of that tool's columns
# is filled. Tools whose columns are absent (e.g. BLASTp/HH-suite off-tier) are
# simply not listed. Order = display order.
_TOOL_COLUMN_PREFIXES = [
    ("SignalP", ("signalp_",)),
    ("InterProScan", ("interpro_", "pfam_ids")),
    ("pLM-BLAST (ECOD)", ("ecod_",)),
    ("EggNOG", ("eggnog_", "cog_", "kegg_")),
    ("BLASTp", ("blastp_",)),
    ("HH-suite", ("hhsuite_", "hh_", "pdb_")),
]


def generate_text_report(master_csvs, enrichment_file, output_path, tier=""):
    """Generate plain text summary report."""
    # Load and combine all master CSVs
    dfs = []
    for f in master_csvs:
        try:
            dfs.append(pd.read_csv(f))
        except Exception as e:
            logger.warning(f"Could not read {f}: {e}")

    if not dfs:
        with open(output_path, "w") as f:
            f.write("ssign Report\n============\nNo results to report.\n")
        return

    df = pd.concat(dfs, ignore_index=True)
    n = len(df)

    # ── Run metadata line ──
    try:
        from ssign_app import __version__
    except Exception:
        __version__ = "unknown"
    genomes = sorted(df["sample_id"].dropna().astype(str).unique()) if "sample_id" in df.columns else []
    meta_bits = [f"ssign v{__version__}"]
    if tier:
        meta_bits.append(f"{tier} tier")
    meta_bits.append(datetime.now().strftime("%Y-%m-%d %H:%M"))

    lines = [
        "=" * 60,
        "ssign — Secretion-System Identification for Gram Negatives",
        "=" * 60,
        "",
        "  |  ".join(meta_bits),
    ]
    if genomes:
        shown = ", ".join(genomes[:6]) + (f" (+{len(genomes) - 6} more)" if len(genomes) > 6 else "")
        lines.append(f"Genomes ({len(genomes)}): {shown}")
    lines += ["", f"Secreted proteins found: {n}", ""]

    # SS type distribution
    if "nearby_ss_types" in df.columns:
        ss_counts: Counter[str] = Counter()
        for val in df["nearby_ss_types"].dropna():
            for ss in str(val).split(","):
                ss = ss.strip()
                if ss:
                    ss_counts[ss] += 1

        if ss_counts:
            lines.append("Secreted proteins per secretion system type:")
            for ss, count in ss_counts.most_common():
                lines.append(f"  {ss}: {count}")
            lines.append("")

    # Annotation coverage, grouped by tool (only tools whose columns are present)
    cov = []
    for tool, prefixes in _TOOL_COLUMN_PREFIXES:
        cols = [c for c in df.columns if c.startswith(prefixes)]
        if cols:
            covered = int(df[cols].notna().any(axis=1).sum())
            cov.append((tool, covered))
    if cov:
        lines.append(f"Annotation coverage (of {n} secreted proteins):")
        width = max(len(t) for t, _ in cov)
        for tool, covered in cov:
            pct = 100 * covered / max(n, 1)
            lines.append(f"  {tool:<{width}}  {covered}/{n} ({pct:.0f}%)")
        lines.append("")

    # Enrichment summary
    if enrichment_file and os.path.exists(enrichment_file):
        lines.append("Enrichment results:")
        with open(enrichment_file) as f:
            lines.append(f.read())

    lines.append("=" * 60)

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Wrote text report to {output_path}")


def generate_html_report(master_csvs, enrichment_file, output_path):
    """Generate HTML summary report."""
    # Simple HTML wrapping the text report
    text_path = output_path.replace(".html", ".txt")
    if os.path.exists(text_path):
        with open(text_path) as f:
            text_content = f.read()
    else:
        text_content = "No results."

    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>ssign Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        pre {{ background: #f8f9fa; padding: 20px; border-radius: 5px; overflow-x: auto; }}
        .footer {{ color: #7f8c8d; font-size: 0.85em; margin-top: 40px; }}
    </style>
</head>
<body>
    <h1>ssign Report</h1>
    <p>Secretion-System Identification for Gram Negatives</p>
    <pre>{text_content}</pre>
    <div class="footer">
        <p>Generated by ssign pipeline</p>
    </div>
</body>
</html>"""

    with open(output_path, "w") as f:
        f.write(html)

    logger.info(f"Wrote HTML report to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate ssign report")
    parser.add_argument("--master-csvs", nargs="+", required=True)
    parser.add_argument("--enrichment", default="")
    parser.add_argument("--out-html", required=True)
    parser.add_argument("--out-txt", required=True)
    parser.add_argument("--tier", default="", help="Install tier (shown in the report metadata line).")
    args = parser.parse_args()

    generate_text_report(args.master_csvs, args.enrichment, args.out_txt, tier=args.tier)
    generate_html_report(args.master_csvs, args.enrichment, args.out_html)


if __name__ == "__main__":
    main()
